FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ENV NEXT_PUBLIC_API_URL=https://scoreaimanage.onrender.com/api
ENV NODE_ENV=production

RUN npm run build

EXPOSE 7860

ENV PORT=7860
ENV HOSTNAME=0.0.0.0

CMD ["npm", "start"]
